test: check the namespace is not cluttered with min/max
libnvme defined a min/max macro before and exposed to all users.
This has been removed but let's sure it doesn't come back, thus
add a test for this.

Before renaming the macro, the cpp's std::min will fail to compile.
```
./test/cpp.cc: In function ‘int min_compile_test()’:
../src/nvme/util.h:563:19: error: expected unqualified-id before ‘(’ token
  563 | #define min(x, y) ((x) > (y) ? (y) : (x))
```
Signed-off-by: Jian Zhang <zhangjian.3032@bytedance.com>
[wagi: move the test to a seperate file]
Signed-off-by: Daniel Wagner <wagi@kernel.org>