README: Fix include file location for plugin
If the CMD_INC_FILE is defined with file name without location, the
following error will happen.

In file included from plugins/foo/foo-nvme.h:17:0,
                 from plugins/foo/foo-nvme.c:4:
./define_cmd.h:12:34: fatal error: foo-nvme.h: No such file or directory
 #include CMD_INCLUDE(CMD_INC_FILE)
                                  ^

Signed-off-by: Minwoo Im <minwoo.im@samsung.com>