nvme-topology: fix build error for unused variable
Fix the following build error.

nvme-topology.c: In function ‘uuid_from_systemd’:
nvme-topology.c:766:8: error: unused variable ‘ret’ [-Werror=unused-variable]
  766 |  char *ret;
      |        ^~~

Signed-off-by: Minwoo Im <minwoo.im.dev@gmail.com>