util/types: include missing header for time_t
The musl build fails due to a missing include:

In file included from ../unit/test-uint128.c:8:
../unit/../util/types.h:60:16: error: unknown type name ‘time_t’
   60 | int convert_ts(time_t time, char *ts_buf);
      |                ^~~~~~
../unit/../util/types.h:11:1: note: ‘time_t’ is defined in header ‘<time.h>’; this is probably fixable by adding ‘#include <time.h>’
   10 | #include <libnvme.h>
  +++ |+#include <time.h>
   11 |

Signed-off-by: Daniel Wagner <wagi@kernel.org>