rpmbuild: Enable 'make rpm' to build rpm pkgs #408
- meson is needed higher version then what rpm repo offering (use pip install)
- Enable building static library (default: shared)
- Add gitignore since make rpm generates tar.gz (when it is failed)
- libuuid-devel dose not needed as rpm pkgs
    it could be installed as some files
    if it's not installed, will be downloaded from subprojects of meson
- gcc does not needed as rpm pkgs
    meson detect compiler with meson.get_compiler('c')

error: Failed build dependencies:
gcc is needed by libnvme-1.0-0.x86_64
libuuid-devel is needed by libnvme-1.0-0.x86_64
Makefile:43: recipe for target 'rpm' failed
make: *** [rpm] Error 1

Signed-off-by: Steven Seungcheol Lee <sc108.lee@samsung.com>