rpmbuild: Add json required version that detected from meson
With higher version of json-c, yum install shows required version of it
Error: Package: nvme-2.0-1.el7.x86_64 (/nvme-2.0-1.el7.x86_64)
           Requires: json-c >= 0.14
           Installed: json-c-0.11-4.el7_0.x86_64 (@anaconda)
               json-c = 0.11-4.el7_0

Signed-off-by: Steven Seungcheol Lee <sc108.lee@samsung.com>