nvme-print: Use 'unsigned int' instead of 'unsigned'
Fix for the checkpatch review error below.
  Error: WARNING: Prefer 'unsigned int' to bare use of 'unsigned'

Signed-off-by: Tokunori Ikegami <ikegami.t@gmail.com>