nvme-print: Adding enum nvme_feat
This patch switch the feature_id into an named enum called nvme_feat.

Having named enum ease the implementation as Werror=switch compile flag will detect forgotten case statements.

A build failure looks like :
	nvme-print.c:4525:2: error: enumeration value ‘NVME_FEAT_RRL’ not handled in switch [-Werror=switch]

This patch adds the NVME_FEAT_SANITIZE & NVME_FEAT_RRL inside nvme_feature_show_fields().

A NVME_FEAT_NONE=0 value is added to give a neutral/default value when needed.

Signed-off-by: Erwan Velu <e.velu@criteo.com>