meson: libsystemd <= 219 does not support sd-bus, sd-event
build error below
./dist-unpack/libnvme-1.0/src/nvme/mi-mctp.c
../dist-unpack/libnvme-1.0/src/nvme/mi-mctp.c:25:10: fatal error: systemd/sd-event.h: No such file or directory
   25 | #include <systemd/sd-event.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
[740/769] Compiling C object src/libnvme.so.1.0.0.p/nvme_tree.c.o

MCTP defined values are used when CONFIG_LIBSYSTEMD is defined