MAINT: Fix format compile warning error on 32 bit system
Since the following %lx format warning error was caused on 64 bit system.

  error: format ‘%lx’ expects argument of type ‘long unsigned int’,
  but argument 2 has type ‘long long unsigned int’ [-Werror=format=]

So fix this by using %" PRIx64 " format instead as generic.

Signed-off-by: Tokunori Ikegami <ikegami.t@gmail.com>